# List of POP spreadsheet headers. ONLY change values in the
# right-hand column.
# DO NOT!!! change the left hand values
#
# If a spreadsheet lacks one of these header columns; it will not be
# processed.
---
:header_definitions:
  :file_name:                             image title
  :url_to_catalog:                        url to catalog
  :image_type:                            image type
  :copy_call_number:                      copy:call number
  :copy_volume_number:                    copy:volume number
  :copy_current_repository:               copy:current repository
  :copy_current_collection:               copy:current collection
  :copy_author:                           copy:author
  :copy_title:                            copy:title
  :copy_place_of_publication:             copy:place of publication
  :copy_date_of_publication:              copy:date of publication
  :copy_printer_publisher:                copy:printer/publisher
  :evidence_location_in_book:             evidence:location in book
  :evidence_format:                       evidence:format
  :evidence_type:                         evidence:type
  :evidence_transcription:                evidence:transcription
  :evidence_individual_associated_name:   evidence:individual associated name
  :evidence_organization_associated_name: evidence:organization associated name
  :evidence_family_associated_name:       evidence:family associated name
  :evidence_date_associated:              evidence:associated date
  :evidence_place_associated:             evidence:associated place
  :evidence_creator_of_evidence:          evidence:creator
  :evidence_description:                  evidence:description
  :evidence_status:                       evidence:status
  :id_date:                               id:date
  :id_place:                              id:place
  :id_individual_owner:                   id:individual:owner
  :id_organization_owner:                 id:organization:owner
  :id_individual_donor:                   id:individual:donor
  :id_organization_donor:                 id:organization:donor
  :id_individual_recipient:               id:individual:recipient
  :id_organization_recipient:             id:organization:recipient
  :id_individual_seller:                  id:individual:seller
  :id_organization_seller:                id:organization:seller
  :id_individual_selling_agent:           id:individual:selling agent
  :id_organization_selling_agent:         id:organization:selling agent
  :id_individual_buyer:                   id:individual:buyer
  :id_organization_buyer:                 id:organization:buyer
  :comments:                              comments

# Required headers definitions are those keys that must appear on the
# left in the list above; these are the headers that must be defined
# for the pop uploader to work.
:required_header_definitions:
  - file_name
  - url_to_catalog
  - image_type
  - copy_call_number
  - copy_volume_number
  - copy_current_repository
  - copy_current_collection
  - copy_author
  - copy_title
  - copy_place_of_publication
  - copy_date_of_publication
  - copy_printer_publisher
  - evidence_location_in_book
  - evidence_format
  - evidence_type
  - evidence_transcription
  - evidence_date_associated
  - evidence_place_associated
  - evidence_creator_of_evidence
  - evidence_description
  - evidence_status
  - id_date
  - id_place

:tag_headers:
  - image_type
  - copy_call_number
  - copy_current_repository
  - copy_current_collection
  - copy_author
  - copy_place_of_publication
  - copy_date_of_publication
  - evidence_format
  - evidence_individual_associated_name
  - evidence_organization_associated_name
  - evidence_family_associated_name
  - evidence_date_associated
  - evidence_place_associated
  - evidence_creator_of_evidence
  - evidence_status
  - id_date
  - id_place
  - id_individual_owner
  - id_organization_owner
  - id_individual_donor
  - id_organization_donor
  - id_individual_recipient
  - id_organization_recipient
  - id_individual_seller
  - id_organization_seller
  - id_individual_selling_agent
  - id_organization_selling_agent
  - id_individual_buyer
  - id_organization_buyer

:associated_name_headers:
  - evidence_individual_associated_name
  - evidence_organization_associated_name
  - evidence_family_associated_name

:identified_name_headers:
  - id_individual_owner
  - id_organization_owner
  - id_individual_donor
  - id_organization_donor
  - id_individual_recipient
  - id_organization_recipient
  - id_individual_seller
  - id_organization_seller
  - id_individual_selling_agent
  - id_organization_selling_agent
  - id_individual_buyer
  - id_organization_buyer

:owner_headers:
  - id_individual_owner
  - id_organization_owner

:donor_headers:
  - id_individual_donor
  - id_organization_donor

:recipient_headers:
  - id_individual_recipient
  - id_organization_recipient

:seller_headers:
  - id_individual_seller
  - id_organization_seller

:selling_agent_headers:
  - id_individual_selling_agent
  - id_organization_selling_agent

:buyer_headers:
  - id_individual_buyer
  - id_organization_buyer
