# List of POP spreadsheet headers. ONLY change values in the
# right-hand column.
# DO NOT!!! change the left hand values
#
# If a spreadsheet lacks one of these header columns; it will not be
# processed.
---
:header_definitions:
  :file_name:                 "image file name"
  :url_to_catalog:            "url to catalog"
  :copy_current_repository:   "copy: current repository"
  :copy_current_collection:   "copy: current collection"
  :copy_current_owner:        "copy: current owner"
  :copy_current_location:     "copy: current geographic location"
  :copy_call_number:          "copy: call number/shelf mark"
  :copy_volume_number:        "copy: volume number"
  :copy_other_id:             "copy: other id"
  :copy_author:               "copy: author"
  :copy_title:                "copy: title"
  :copy_place_of_publication: "copy: place of publication"
  :copy_date_of_publication:  "copy: date of publication"
  :copy_printer_publisher:    "copy: printer/publisher/scribe"
  :evidence_location_in_book: "evidence: location in book"
  :evidence_format:           "evidence: format"
  :evidence_date:             "evidence: date"
  :evidence_place:            "evidence: place"
  :evidence_type:             "evidence: content type"
  :evidence_transcription:    "evidence: transcription"
  :evidence_citation:         "evidence: citation"
  :evidence_comments:         "evidence: comments"
  :id_owner:                  "id: owner"
  :id_librarian:              "id: librarian"
  :id_bookseller:             "id: bookseller/auction house"
  :id_binder:                 "id: binder"
  :id_other:                  "id: other"
  :id_unknown:                "id: role unknown"
  :id_viaf_link:              "id: viaf authority link"

# Required headers definitions are those headers that must be defined
# for the pop uploader to work.
:required_header_definitions:
  - file_name
  - url_to_catalog
  - copy_call_number
  - copy_volume_number
  - copy_current_repository
  - copy_current_collection
  - copy_author
  - copy_title
  - copy_place_of_publication
  - copy_date_of_publication
  - copy_printer_publisher
  - evidence_location_in_book
  - evidence_format
  - evidence_type
  - evidence_transcription

:required_values:
  - copy_current_repository
  - copy_call_number
  - evidence_format
  - copy_title

:tag_headers:
  - copy_call_number
  - copy_current_repository
  - copy_current_collection
  - copy_current_owner
  - copy_author
  - copy_place_of_publication
  - copy_date_of_publication
  - copy_printer_publisher
  - evidence_format
  - evidence_date
  - evidence_place
  - evidence_type
  - id_owner
  - id_librarian
  - id_bookseller
  - id_binder
  - id_other
  - id_unknown

# Decide what to do about other
:identified_name_headers:
  - id_owner
  - id_librarian
  - id_bookseller
  - id_binder
  - id_other
  - id_unknown

:owner_headers:
  - id_owner

:seller_headers:
  - id_bookseller

:otherid_headers:
  - id_other
