# List of POP spreadsheet headers. ONLY change values in the
# right-hand column.
# DO NOT!!! change the left hand values
#
# If a spreadsheet lacks one of these header columns; it will not be
# processed.
---
:header_definitions:
  :file_name:                 "image file name"
  :url_to_catalog:            "url to catalog"
  :image_type:                "evidence: image category"
  :copy_call_number:          "copy: call number/shelf mark"
  :copy_volume_number:        "copy: volume number"
  :copy_current_repository:   "copy: current repository"
  :copy_current_collection:   "copy: current collection"
  :copy_author:               "copy: author"
  :copy_title:                "copy: title"
  :copy_place_of_publication: "copy: place of publication"
  :copy_date_of_publication:  "copy: date of publication"
  :copy_printer_publisher:    "copy: printer/publisher"
  :evidence_location_in_book: "evidence: location in book"
  :evidence_format:           "evidence: format"
  :evidence_type:             "evidence: content type"
  :evidence_transcription:    "evidence: transcription"
  :evidence_associated_name:  "evidence: associated name"
  :evidence_date_associated:  "evidence: associated date"
  :evidence_place_associated: "evidence: associated place"
  :evidence_description:      "evidence: description"
  :evidence_citation:         "evidence: reference citation"
  :evidence_comments:         "evidence: comments"
  :id_date:                   "id: date"
  :id_place:                  "id: place"
  :id_owner:                  "id: owner"
  :id_donor:                  "id: donor"
  :id_recipient:              "id: recipient"
  :id_seller:                 "id: seller"
  :id_selling_agent:          "id: selling agent"
  :id_buyer:                  "id: buyer"
  :id_bindier:                "id: binder"
  :id_viaf_link:              "id: viaf authority link"


# Required headers definitions are those headers that must be defined
# for the pop uploader to work.
:required_header_definitions:
  - file_name
  - url_to_catalog
  - image_type
  - copy_call_number
  - copy_volume_number
  - copy_current_repository
  - copy_current_collection
  - copy_author
  - copy_title
  - copy_place_of_publication
  - copy_date_of_publication
  - copy_printer_publisher
  - evidence_location_in_book
  - evidence_format
  - evidence_type
  - evidence_transcription
  - evidence_date_associated
  - evidence_place_associated
  - evidence_description
  - id_date
  - id_place

:required_values:
  - copy_current_repository
  - copy_call_number
  - evidence_format
  - copy_title

:tag_headers:
  - image_type
  - copy_call_number
  - copy_current_repository
  - copy_current_collection
  - copy_author
  - copy_place_of_publication
  - copy_date_of_publication
  - evidence_format
  - evidence_associated_name
  - evidence_date_associated
  - evidence_place_associated
  - id_date
  - id_place
  - id_owner
  - id_donor
  - id_recipient
  - id_seller
  - id_selling_agent
  - id_buyer

:associated_name_headers:
  - evidence_associated_name

:identified_name_headers:
  - id_owner
  - id_donor
  - id_recipient
  - id_seller
  - id_selling_agent
  - id_buyer

:owner_headers:
  - id_owner

:donor_headers:
  - id_donor

:recipient_headers:
  - id_recipient

:seller_headers:
  - id_seller

:selling_agent_headers:
  - id_selling_agent

:buyer_headers:
  - id_buyer
